- hosts: all
  sudo: true
  vars:
    document_root: /consul/vars
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install python
      apt: name=python state=present
    - name: install supervisord
      apt: name=supervisor state=present
    - name: Add the user 'testuser'
      user:
            name: testuser

    - name: Set Time Zone
      copy: content='Asia/Kolkata'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

  tasks:
    - copy:
        src: test1
        dest: /home/testuser/

    - include: consul/tasks/main.yml

    - name: Copy systemd conf
      template:
          src: consul.service.j2
          dest: /etc/systemd/system/consul.service

